login_path:
    path: /
    methods: [GET]
    controller: App\Controller\SecurityController::login

security:
    path: /security
    methods: [POST]
    controller: App\Controller\SecurityController

app_admin:
    path: /admin
    methods: [GET]
    controller: App\Controller\AdminController

page1:
    path: /page/1
    methods: [GET]
    controller: App\Controller\Page1Controller

page2:
    path: /page/2
    methods: [GET]
    controller: App\Controller\Page2Controller